stages:
  - test1
  - test2

k6-test-1: 
  image: 
    name: loadimpact/k6
    entrypoint: [""]
  script: 
    - "k6 run admin_suli_es_kepek_test.js"
  only: 
    - master
  stage: test1
  tags: 
    - gitlab-org-docker

k6-test-2: 
  image: 
    name: loadimpact/k6
    entrypoint: [""]
  script: 
    - "k6 run admin_arlista_test.js"
  only: 
    - master
  stage: test2
  tags: 
    - gitlab-org-docker
